name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '5.0.x'
        include-prerelease: true

    - name: Setup Node.js environment
      uses: actions/setup-node@v2.4.1

    - name: Test
      run: dotnet fsi build.fsx test
